### ISSUE TITLE
To ensure a good performance of SimpleDB as a developer, I can use XUnit to run both unit and integration tests

### ISSUE THREAD

**Issue by Niels420** [ITU-BDSA2024-GROUP1/Chirp#12]
Acceptance:
- [ ] There are tests for both the Store and Read functions from the CSVdatabase

Done:
- [x] Both the Store and Read tests pass

**Comment by CptShini** [comment]
Just @ me if you want help with this one

**Comment by CptShini** [comment]
Finished merging this with the main branch
