### ISSUE TITLE
To ensure database consistency as a developer, I can make CsvDatabase follow the singleton design pattern

### ISSUE THREAD

**Issue by Cybermanboss** [ITU-BDSA2024-GROUP1/Chirp#13]
Acceptance: 
- [x] CsvDatabase has a singleton
- [x] All accesses to CsvDatabase go to the singleton

Done:
- [x] The program can access the database without issue

**Comment by CptShini** [comment]
The code in and of itself is done... but in the meantime, tests have been writting for the old version, and they don't really make sense after the refactoring.

**Comment by CptShini** [comment]
Since this seems to have been properly integrated into main, including test functionality, I'm just going to close this!
