### ISSUE TITLE
To ensure a stable product, as a developer I can refactor tests to account for the changes to Chirp.CLI and SimpleDB

### ISSUE THREAD

**Issue by Emilbks** [ITU-BDSA2024-GROUP1/Chirp#21]
Acceptance:
- [x] Refactor the Chirp.CLI tests to account for web app
- [x] Refactor the SimpleDB tests to account for web app

Done:
- [x] All Chirp.CLI tests run successfully 
- [x] All SimpleDB test run successfully

**Comment by CptShini** [comment]
I'm also adding tests for a new Chirp.Core Library

**Comment by CptShini** [comment]
End2End tests still don't work :/

**Comment by CptShini** [comment]
They finally work :')
